In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
import torch

A = torch.tensor([[1, 0, 2],
                  [0, 0, 0],
                  [1, 2, 3]])

def drop_column(A: torch.tensor) -> torch.tensor:
    x, y = A.shape
    zero_counts = []

    # Count the number of zeros in each column
    for i in range(y):
        zero_counts.append(torch.sum(A[:, i] == 0))
        print(zero_counts)

drop_column(A)

[tensor(1)]
[tensor(1), tensor(2)]
[tensor(1), tensor(2), tensor(1)]


In [15]:
import torch

x = torch.rand(8)
half = int(len(x)/2)

y = x[:half]
z = x[half:]

result = torch.stack([y,z])
result

tensor([[0.3422, 0.5048, 0.9253, 0.7639],
        [0.5544, 0.1896, 0.5815, 0.7741]])

In [17]:
import torch

matrix=torch.tensor([[1,2],
                    [3,4],
                    [5,6],
                    [8,9],
                    [10,11],
                    [6,9]])
x, y = matrix.shape
if x % 2 == 0:
    half_columns = x//2
    listOfSums = []
    for i in range(0, half_columns):
        print(i)
        sums = torch.sum(matrix[2*i, :])
        listOfSums.append(sums)
    result = torch.tensor(listOfSums)
    print(result)

else:
    half_columns = x//2
    listOfSums = []
    for i in range(0, half_columns+1):
        print(i)
        sums = torch.sum(matrix[2*i, :])
        listOfSums.append(sums)
    result = torch.tensor(listOfSums)
    print(result)

0
1
2
tensor([ 3, 11, 21])


In [28]:
x = torch.tensor([[1.0, 2.0, 3.0], [1.0, 5.0, 3.0]])
mean = torch.mean(x,1)
result = torch.argmax(mean)
highestidx

tensor([2., 3.])


tensor(1)

In [39]:
import torch

# Example 2D tensor
A = torch.tensor([[0, 0, 0], 
                  [1, 2, -1]])

# Get the maximum values of each row
max_values, max_indices = torch.max(A, dim=1)

max_values = max_values.unsqueeze(0)
max_values = max_values.t()

maxSubtracted = A - max_values
print(maxSubtracted)

exp = torch.exp(maxSubtracted)
print(exp)

expSum = torch.sum(exp, dim=1)
print(expSum)

expSum = expSum.unsqueeze(0)
expSum = expSum.t()

results = exp/expSum

results


tensor([[ 0,  0,  0],
        [-1,  0, -3]])
tensor([[1.0000, 1.0000, 1.0000],
        [0.3679, 1.0000, 0.0498]])
tensor([3.0000, 1.4177])


tensor([[0.3333, 0.3333, 0.3333],
        [0.2595, 0.7054, 0.0351]])

In [57]:
#Batch norm!!!!!!
data = torch.tensor([[1.0, 4],
                    [2, 5],
                    [3, 6]])
epsilon = 0.00001

dataLen = data.shape[1]
mean = torch.mean(data, dim=0, keepdim=True)
variance = torch.sum((data-mean)**2, dim=0)/dataLen
#var = torch.var(data, dim=0, unbiased=True)
print(dataLen)
print(mean)
print(variance)

result = (data-mean)/((variance + epsilon)**0.5)
print(result)

2
tensor([[2., 5.]])
tensor([1., 1.])
tensor([[-1.0000, -1.0000],
        [ 0.0000,  0.0000],
        [ 1.0000,  1.0000]])
